apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.kube.namespace }}
  labels:
    {{- include "common.labels" . }}
spec:
  type: ClusterIP
  ports:
    - name: 'http'
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Values.appName }}